name: lando-certs
proxy:
  nginx:
    - lando-certs.lndo.site:8080
    - hostname: lando-certs-2.lndo.site
      port: 8080
services:
  alpine:
    api: 4
    image: alpine:3.20
    command: env
  centos:
    api: 4
    image: centos:7
    command: sleep infinity
  debian:
    api: 4
    image: debian:bookworm-slim
    command: sleep infinity
  fedora:
    api: 4
    image: fedora:40
    command: sleep infinity
  ol:
    api: 4
    image: oraclelinux:9-slim
    command: sleep infinity
  nginx:
    api: 4
    image:
      imagefile: nginxinc/nginx-unprivileged:1.26.1
      context:
        ./default-ssl.conf:/etc/nginx/conf.d/default.conf
    user: nginx
    ports:
      - 8080/http
      - 8443/https

plugins:
  "@lando/core": "../.."
  "@lando/healthcheck": "../../plugins/healthcheck"
  "@lando/networking": "../../plugins/networking"
  "@lando/proxy": "../../plugins/proxy"
  "@lando/scanner": "../../plugins/scanner"
