name: lando-certs
proxy:
  nginx:
    - lando-certs.lndo.site:8080
    - hostname: lando-certs-2.lndo.site
      port: 8080
events:
  post-start:
    - nginx: env | grep LANDO | sort
    - debian: tail -f /dev/null &
    - web3: tail -f /dev/null &
services:
  alpine:
    api: 4
    image: alpine:3.20
    command: sleep infinity
  debian:
    api: 4
    image:
      imagefile: |
        FROM debian:bookworm-slim
        RUN apt update -y && apt install -y procps
    command: sleep infinity
  fedora:
    api: 4
    image: fedora:40
    command:
      - sleep
      - infinity
  ol:
    api: 4
    image: oraclelinux:9-slim
    command: sleep infinity
  nginx:
    api: 4
    primary: true
    certs: /certs/cert.crt
    build:
      app: |
        echo "app build"
        sh -c "env | grep LANDO | sort"
    hostnames:
      - bobthing
    image:
      imagefile: nginxinc/nginx-unprivileged:1.26.1
      context:
        - ./default-ssl.conf:/etc/nginx/conf.d/default.conf
    user: nginx
    ports:
      - 8080/http
      - 8443/https

  web3:
    api: 3
    type: lando
    ssl: true
    sslExpose: false
    services:
      image: bitnami/nginx
      command: /opt/bitnami/scripts/nginx/entrypoint.sh /opt/bitnami/scripts/nginx/run.sh
      ports:
        - "8080"
      user: root

tooling:
  env:
    service: nginx
  backgrounder:
    service: debian
    cmd: tail -f /dev/null &
  backgrounder2:
    service: web3
    cmd: tail -f /dev/null &

plugins:
  "@lando/core": "../.."
  "@lando/healthcheck": "../../plugins/healthcheck"
  "@lando/networking": "../../plugins/networking"
  "@lando/proxy": "../../plugins/proxy"
  "@lando/scanner": "../../plugins/scanner"
