name: lando-certs
services:
  # debian:
  #   api: 4
  #   image: debian:bookworm-slim
  #   certs: true
  alpine:
    api: 4
    image: alpine:3.20
    certs: true

plugins:
  "@lando/core": "../.."
  "@lando/healthcheck": "../../plugins/healthcheck"
  "@lando/networking": "../../plugins/networking"
  "@lando/proxy": "../../plugins/proxy"
  "@lando/scanner": "../../plugins/scanner"
