name: service-v4

services:
  node:
    type: node:16
    # build_as_root:
    #   - fail
    run_as_root:
      - echo "frank"

  web2:
    api: 4

    # type: what about webserver-v4? service-v4?
    image: |
      FROM nginx:1.17
      ENV LANDO_RUN 6
      RUN apt-get update -y && apt-get install openssl -y
    install:
      composer: 1.10.2

    verify-dependecy: openssl
    addscript: add-cert.sh


  web:
    api: 4
    # type: what about webserver-v4? service-v4?
    image: |
      FROM nginx:1.17
      ENV LANDO_RUN 8
      RUN echo "YES" > /usr/share/nginx/html/index.html
      RUN apt-get update -y && apt-get install openssl -y

    # NOTE: if below is to work we need a image build step to complete first so that
    # the image in docker compose is set to that locally built image

    # image: |
    #   DOCKERFILE CONTENT?
    # if exists then write the file?

    # image: /path/to/dockerfile
    # # full syntax:
    # image:
    #   dockerfile:
    #   args:

    # either this is still a string or its an object



    # 1. what does the "core" lando v4 service do?
    # 1. user mapping
    #    which is host/container perm syncing eg the container should run as the host user and its volumes should be owned by the host user
    # 2. app-mount
    # 3?. shared-home or something? universal | app | service | false|disabled|none?\
    # 4. data-persistance?

    # build:

    # spin up two containers php-apache and mariadb
      # user mapping
      # mount home/persisiten data
      # localhost


    # 5. dependencies?
    # 7. build steps

    # # other stuff we have
    # 6. overrides?

    # 8. locahost assignment

    # 9. scanner -> healthcheck?

    # 2. what goes into the dockerfile and what goes into compose?
      # self contained portable service vs application

    # dockerfile:
    #   # aht goes here?
    #   - run: myscript.sh

    # compose:
    #   image: |
    #     FROM thinweg

    #     wefoiwejg

    #     wegweg
    #     weg
    #     weg
    #     weg


    #   # Required. See Below
    #   command: docker-php-entrypoint apache2-foreground
    #   ports:
    #     - '80'



    # we will support the below?
    # volumes:
    #   my-volume:
    # networks:
    #   my-network:


# @TODO: what about these?
# env_file:
#   - environment/moar.env
# compose:
#   - docker-compose/moar.yml
