name: service-v4
services:
  web1:
    api: 4
    image:
      dockerfile: nginx:1.15
      context:
        - ./folder
        - ./folder:thing
        - file1:/file2
        - src: file1
          dest: file3
        - source: file1
          destination: file4

      groups:
        - bob: 99
        - name: 'configure'
          description: 'configure linux packages? certs? php-extensions'
          user: root
          stage: image
        - name: 'configure-me-first'
          description: 'configure linux packages? certs? php-extensions'
          user: root
          weight: -100

      steps:
       # raw pass in
        - instructions: |
            COPY file4 /file2
            RUN touch /me
        - instructions:
          - env:
              key1: value3
              key2: value3
          - run: env
          - run:
            - 'stat'
            - '/file2'

        # default stage?
        - instructions: |
            ENV TEST=3
            RUN env

        # custom weights
        - instructions: RUN cat /stuff
          weight: 1001
        - instructions: |
            RUN echo "test" > /stuff
          weight: 999
        - instructions: |
            RUN echo "test" > /stuff2
          weight: 1
        - instructions: |
             RUN cat /stuff2
          weight: 9999

        - group: bob-4-nginx-before
          instructions: |
             RUN env
        - group: bob-after-3
          instructions: |
             RUN env


        - group: frank
          instructions: |
             RUN env
        - group: bob
          instructions: |
             RUN env
        - group: configure
          instructions: |
             RUN echo "BOB=BOBBED > /etc/environment"

        # use existing group
        # - group: default
        #   instructions: |
        #     ENV TEST=1
        # - group: default
        #   instructions:
        #     - run: 'env'


        # assume default group
        # - group: default
        #   instructions: |
        #     ENV TEST=1

        # - group: init-3-after/before-user
        #   instructions:
        #     - run: other tihg
        #     - env:
        #         key1: value3
        #         key2: value3

        # # using a new one
        # # no weight = end of the groups?
        # - instructions:
        #   - run: other tihg
        #   - env:
        #       key1: value3
        #       key2: value3
        #   weight: 100


    environment:
      HELLO: there
    ports:
      - 80

  # web2:
  #   api: 4
  #   image: |
  #     FROM nginx:1.17
  #     ENV LANDO_RUN 6
  #     RUN apt-get update -y && apt-get install openssl -y
  #   ports:
  #     - 80

  # web3:
  #   api: 4
  #   image:
  #     dockerfile: |
  #       FROM nginx:1.17
  #       ENV LANDO_RUN 6
  #       RUN apt-get update -y && apt-get install openssl -y
  #     args: weewg, wegweg,
  #     build-steps:
  #     build-files:
  #       - /log.sh
  #     ports:
  #       - 80

  # web4:
  #   api: 4
  #   build:
  #     dockerfile: |
  #       FROM nginx:1.20
  #       ENV LANDO_RUN 6
  #       RUN apt-get update -y && apt-get install openssl -y

  # web5:
  #   api: 4
  #   ports:
  #     - 80
  #   build:
  #     dockerfile: ./images/Dockerfile

    # volumes:
    #   - ./:/app
    #   - data-voluime:/here

    # app-mount: /app
    # persistent-data:
    # environment:
    #   weoigj


    # build:
    #   files:
    #     php=exnteison=stcitp:/place
    #   image: |


    #   image:
    #     - root: stuff
    #     - me: stuff

    # command:
    # entrypoint:





volumes:
  test:
networks:
  test:

