name: Core Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        lando-version:
          # - 3-slim
          # uncomment to test against edge cli
          - 3-edge-slim
          # uncomment to test against dev cli
          # - 3-dev-slim
        leia-test:
          - badname
          - build
          - cache
          - certs
          - config
          - debug
          - envfile
          # - environment
          - events
          - exec
          - experimental
          - healthcheck
          - host
          # - hostnames
          - info
          - init-github
          - init-remote
          - keys
          - l337
          - lando-v4
          - landofile
          - landofile-custom
          - list
          - logs
          - long-name
          - mounts
          - networking
          - no-services
          - orchestrator
          - plugins
          - proxy
          - rebuild
          - renderer
          - recipes
          - release-channel
          - restart
          - scanner
          - security
          - sql-helpers
          - ssh
          - storage
          - tooling
          - update
          - version
        node-version:
          - "20"
        os:
          # - macos-13
          # - macos-14
          - ubuntu-24.04
          # - windows-2022
        shell:
          - bash

        # TODO: includes for also running windows tests on cmd/powershell?

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Install pkg dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile
      - name: Package into node binary
        uses: lando/pkg-action@v5
        id: pkg-action
        with:
          entrypoint: bin/lando
          node-version: ${{ matrix.node-version }}
          options: --options dns-result-order=ipv4first
          upload: false
          pkg: "@yao-pkg/pkg@5.15.0"
      - name: Install full deps
        run: |
          npm clean-install --prefer-offline --frozen-lockfile
          echo "${{ steps.pkg-action.outputs.file }}"
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v3
        with:
          lando-version: ${{ steps.pkg-action.outputs.file }}
          auto-setup: lando plugin-add @lando/core@file:${{ github.workspace }} && lando setup
          telemetry: false
          config: |
            setup.skipCommonPlugins=true
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        env:
          GITHUB_PAT: ${{ secrets.KYBER_AMPLIFICATION_MATRIX }}
          GITHUB_KEY_NAME: "${{ github.sha }}${{ matrix.os }}"
        with:
          leia-test: "./examples/${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: ${{ matrix.shell }}
          stdin: true
