name: Setup Windows Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        lando-version:
          # - 3-slim
          # uncomment to test against bleeding edge cli
          - 3-dev-slim
        leia-test:
          - setup-windows
        node-version:
          - "18"
        os:
          - windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile
      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v3
        with:
          auto-setup: false
          lando-version: ${{ matrix.lando-version }}
          telemetry: false
      # - name: TESTS
      #   shell: powershell
      #   run: |
      #     $ErrorActionPreference = "Stop"

      #     # Should dogfood the core plugin we are testing against
      #     lando plugin-add "@lando/core@file:${{ github.workspace }}"

      #     # Should be able to run lando setup
      #     lando setup -y --skip-networking --skip-common-plugins --debug

      #     # Should have installed Docker Desktop
      #     Test-Path "$Env:ProgramFiles\Docker\Docker\Docker Desktop.exe"
      #     & "$Env:ProgramFiles\Docker\Docker\resources\bin\docker.exe" --version

      #     # Should have installed Docker Compose
      #     Get-ChildItem -Path "$HOME/.lando/bin" -Filter "docker-compose-v2*" -Recurse | ForEach-Object {
      #       $dc = $_.FullName
      #       & $dc version
      #     }

      #     # Should have created the Lando Development CA
      #     Test-Path "$HOME/.lando/certs/LandoCA.crt"

      #     # Should have installed the Lando Development CA
      #     certutil -store Root | findstr /C:"Lando Development CA"

      #     # Should have created the Lando Development CA
      #     Test-Path "$HOME/.lando/certs/LandoCA.crt2"

      # - name: Run Leia Tests
      #   uses: lando/run-leia-action@v2
      #   with:
      #     leia-test: "./examples/${{ matrix.leia-test }}/README.md"
      #     cleanup-header: "Destroy tests"
      #     debug: true
      - name: Run Leia Tests
        shell: powershell
        run: |
          npx leia --version
          npx leia "./examples/${{ matrix.leia-test }}/README.md" \
            --setup-header=Start,Setup,This is the dawning \
            --test-header=Test,Validat,Verif \
            --cleanup-header=Destroy tests \
            --shell=powershell \
            --retry=1 \
            --stdin \
            --debug
